import type { GameState, Card, Rank, Suit } from "../../../types/game";

export const createMockGame = (): GameState => {
  // Create the hands array first with realistic mixed card distributions
  const hands = [
    [
      { rank: 'A', suit: '♠' },
      { rank: 'K', suit: '♠' },
      { rank: 'Q', suit: '♠' },
      { rank: 'J', suit: '♠' },
      { rank: '10', suit: '♠' },
      { rank: 'A', suit: '♥' },
      { rank: 'K', suit: '♥' },
      { rank: 'Q', suit: '♥' },
      { rank: 'A', suit: '♦' },
      { rank: 'K', suit: '♦' },
      { rank: 'A', suit: '♣' },
      { rank: 'K', suit: '♣' },
      { rank: 'Q', suit: '♣' }
    ],
    [
      { rank: '9', suit: '♠' },
      { rank: '8', suit: '♠' },
      { rank: '7', suit: '♠' },
      { rank: '6', suit: '♠' },
      { rank: '5', suit: '♠' },
      { rank: 'J', suit: '♥' },
      { rank: '10', suit: '♥' },
      { rank: '9', suit: '♥' },
      { rank: '8', suit: '♥' },
      { rank: 'Q', suit: '♦' },
      { rank: 'J', suit: '♦' },
      { rank: '10', suit: '♦' },
      { rank: 'J', suit: '♣' }
    ],
    [
      { rank: '4', suit: '♠' },
      { rank: '3', suit: '♠' },
      { rank: '2', suit: '♠' },
      { rank: '7', suit: '♥' },
      { rank: '6', suit: '♥' },
      { rank: '5', suit: '♥' },
      { rank: '4', suit: '♥' },
      { rank: '3', suit: '♥' },
      { rank: '2', suit: '♥' },
      { rank: '9', suit: '♦' },
      { rank: '8', suit: '♦' },
      { rank: '7', suit: '♦' },
      { rank: '6', suit: '♦' }
    ],
    [
      { rank: '5', suit: '♦' },
      { rank: '4', suit: '♦' },
      { rank: '3', suit: '♦' },
      { rank: '2', suit: '♦' },
      { rank: '9', suit: '♣' },
      { rank: '8', suit: '♣' },
      { rank: '7', suit: '♣' },
      { rank: '6', suit: '♣' },
      { rank: '5', suit: '♣' },
      { rank: '4', suit: '♣' },
      { rank: '3', suit: '♣' },
      { rank: '2', suit: '♣' },
      { rank: '10', suit: '♣' }
    ]
  ];

  return {
    id: 'test-game-1',
    status: 'PLAYING',
    gameMode: 'PARTNERS',
    currentPlayer: 'user-1',
    currentTrick: [],
    completedTricks: [],
    rules: {
      gameType: 'REGULAR',
      allowNil: true,
      allowBlindNil: true,
      numHands: 8,
      coinAmount: 100,
      bidType: 'REGULAR'
    },
    round: 1,
    currentRound: 1,
    maxPoints: 500,
    minPoints: -500,
    team1TotalScore: 0,
    team2TotalScore: 0,
    team1Bags: 0,
    team2Bags: 0,
    rated: false,
    creatorId: 'user-1',
    hands: hands,
    players: [
      {
        id: 'user-1',
        name: 'Test Player 1',
        username: 'Test Player 1',
        avatarUrl: '/default-pfp.jpg',
        seatIndex: 0,
        position: 0,
        team: 0,
        isDealer: false,
        hand: hands[0] as Card[],
        bid: 3,
        tricks: 0,
      },
      {
        id: 'user-2',
        name: 'Test Player 2',
        username: 'Test Player 2',
        avatarUrl: '/default-pfp.jpg',
        seatIndex: 1,
        position: 1,
        team: 1,
        isDealer: false,
        hand: hands[1] as Card[],
        bid: 2,
        tricks: 0,
      },
      {
        id: 'user-3',
        name: 'Test Player 3',
        username: 'Test Player 3',
        avatarUrl: '/default-pfp.jpg',
        seatIndex: 2,
        position: 2,
        team: 0,
        isDealer: false,
        hand: hands[2] as Card[],
        bid: 4,
        tricks: 0,
      },
      {
        id: 'user-4',
        name: 'Test Player 4',
        username: 'Test Player 4',
        avatarUrl: '/default-pfp.jpg',
        seatIndex: 3,
        position: 3,
        team: 1,
        isDealer: false,
        hand: hands[3] as Card[],
        bid: 4,
        tricks: 0,
      }
    ],
    bidding: {
      currentBidderIndex: 0,
      bids: [3, 2, 4, 4],
      totalBids: 13
    },
    play: {
      currentPlayerIndex: 0,
      currentTrick: [],
      tricks: [],
      leadSuit: null
    },
  };
};
