-- AlterTable
ALTER TABLE "BlockedUser" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Card" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "position" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Friend" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "allowBlindNil" BOOLEAN DEFAULT false,
ADD COLUMN     "allowNil" BOOLEAN DEFAULT true,
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "specialRulesApplied" DROP DEFAULT;

-- AlterTable
ALTER TABLE "GamePlayer" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "GameResult" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Round" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Trick" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "trickNumber" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "UserStats" ALTER COLUMN "id" DROP DEFAULT;
