app = 'bux-spades-redis'
primary_region = 'lax'

[build]

[env]
  REDIS_PASSWORD = 'bux-spades-redis-2025'

[[services]]
  protocol = 'tcp'
  internal_port = 6379

  [[services.ports]]
    port = 6379
    handlers = ['tls']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
